### ISSUE TITLE
pkg_ref_cache_DESCRIPTION.R reads "description" instead of "DESCRIPTION"

### ISSUE THREAD

**Issue by ndelcamp** [pharmaR/riskmetric#106] opened 2020-04-29 22:38 UTC
I'm not sure if in some cases the DESCRIPTION file is lower-case, but I think these need to be swapped to upper-case. `pkg_ref("dplyr") %>% as_tibble() %>% assess()` results in the following warning: 
Warning message:
In read.dcf(file.path(x$path, "description")) :
  cannot open compressed file '~/my-R-libs/dplyr/description', probable reason 'No such file or directory'

**Comment by mpadge** [comment] 2020-05-07 14:05
I can confirm that, and see it in all cases searching for the lower-case version, although these files must be upper case for CRAN.

**Comment by dgkf** [comment] 2020-05-08 00:51
Thanks for reporting the issue, @ndelcamp. Looks like an oversight. We'll get this sorted out shortly.

**Comment by dgkf** [comment] 2020-05-10 19:23
This has been resolved in #101. It seems like it was an oversight missed due to differences in operating system filesystem case sensitivity. We'll be more conscious of this moving forward.

**Closed by dgkf** 2020-05-10 19:23 UTC
Labels: Bug
